apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: skeji

build:
  local:
    push: false
  artifacts:
    - image: skeji-business-units
      context: .
      docker:
        dockerfile: build/docker/business-units.Dockerfile

manifests:
  rawYaml:
    - deployment/local/business-units/*.yaml
    - deployment/local/mongo/*.yaml
    - deployment/local/migrate/*.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: business-units
    port: 8080
    localPort: 8080

profiles:
  - name: kind
    activation:
      - kubeContext: kind-skeji-local
    build:
      local:
        push: false
    deploy:
      kubectl: {}
