apiVersion: batch/v1
kind: Job
metadata:
  name: skeji-migrate
  namespace: migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: skeji-migrate
          image: skeji-migrate:latest
          imagePullPolicy: IfNotPresent
          env:
            # ⚠️  LOCAL DEVELOPMENT ONLY - DO NOT USE IN PRODUCTION
            # Production deployments must use Kubernetes Secrets for credentials
            - name: MONGO_URI
              value: mongodb://root:rootpassword@mongo-0.mongo.mongo.svc.cluster.local:27017,mongo-1.mongo.mongo.svc.cluster.local:27017,mongo-2.mongo.mongo.svc.cluster.local:27017/skeji?authSource=admin&replicaSet=rs0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
