apiVersion: batch/v1
kind: CronJob
metadata:
  name: skeji-mongo-migrate
  namespace: mongo
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: skeji-migrate
              image: skeji-migrate:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: MONGO_URI
                  value: mongodb://mongo.mongo.svc.cluster.local:27017
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "500m"
                  memory: "256Mi"
