apiVersion: batch/v1
kind: Job
metadata:
  name: skeji-migrate
  namespace: migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: skeji-migrate
          image: skeji-migrate:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb://root:rootpassword@mongo.mongo.svc.cluster.local:27017/admin?authSource=admin
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
