apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ingress-requests-buffer
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 3600000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pipeline-executor-requests
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: llm-requests
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: gw-to-scrub-layer
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: scrub-layer-to-llm-layer
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    cleanup.policy: delete
    retention.ms: 86400000
