apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: skeji-kafka
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
    strimzi.io/node-pools: "enabled"
spec:
  kafka:
    version: 4.1.0
    config:
      num.partitions: 1
      offsets.topic.replication.factor: 3
      offsets.topic.num.partitions: 50
      transaction.state.log.num.partitions: 50
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      auto.create.topics.enable: "false"

      log.segment.bytes: 67108864
      log.retention.hours: 1
      log.retention.check.interval.ms: 60000
      log.preallocate: false

      log.cleaner.enable: true
      log.cleaner.delete.retention.ms: 3600000
      log.cleaner.min.cleanable.ratio: 0.5
      
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: skeji-kafka-dual
  namespace: kafka
  labels:
    strimzi.io/cluster: skeji-kafka
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: persistent-claim
    size: 2Gi
    deleteClaim: true
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: infra
                    operator: In
                    values:
                      - "true"
