apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: skeji
  namespace: argocd
spec:
  description: Skeji WhatsApp scheduling platform

  sourceRepos:
  - '*'

  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: mongo
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: ServiceAccount
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: autoscaling
    kind: HorizontalPodAutoscaler

  orphanedResources:
    warn: true
