apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: skeji
build:
  local:
    push: false
  artifacts:
    - image: skeji-business-units
      context: .
      docker:
        dockerfile: build/docker/business-units.Dockerfile
deploy:
  kubectl:
    manifests:
      - deployment/local/**/*.yaml
portForward:
  - resourceType: service
    resourceName: business-units
    port: 8080
    localPort: 8080
manifests:
  rawYaml:
    - deployment/local/**/*.yaml

profiles:
  - name: kind
    activation:
      - kubeContext: kind-skeji-local
    build:
      local:
        push: false
    deploy:
      kubectl:
        flags:
          apply:
            - --prune
